### ISSUE TITLE
Setting horizontal and vertical button padding

### ISSUE THREAD

**Issue by aaronstezycki** [inuitcss/objects.buttons#10]
I'd like to see an option to customise this personally, and not let Inuit determine this. At the moment, testing this out, in some cases my horizontal padding is too big. This is set by Inuit, which doubles the `$base-spacing-unit` for `.btn`.

**Comment by nenadjelovac** [comment]
@aaronstezycki you can use [these variables](https://github.com/inuitcss/objects.buttons/blob/master/_objects.buttons.scss#L13-L14) for it.

**Comment by aaronstezycki** [comment]
So, let me clarify a little more. The variables you have mentioned are explicitly for vertical padding of a button. The horizontal padding, (left and right padding) are actually doubled from the above variable on [line 104](https://github.com/inuitcss/objects.buttons/blob/master/_objects.buttons.scss#L104). 

So technically, even when you set small or large defaults, the left and right padding is always going to be double the top and bottom padding. I would like, in some cases, to arbitrarily set top, right, left and bottom padding.

It might be that, if I want fine grained control, that I don't include inuit buttons, and just create my own button object? Thanks for the advice/help.

**Comment by nenadjelovac** [comment]
@aaronstezycki ah, I see. You are right. 

Inuit should be unopinionated as much as possible and design agnostic, so this does seem like it's getting into way of making that happen.

> It might be that, if I want fine grained control, that I don't include inuit buttons, and just create my own button object?

That would be a workaround at the time being.

**Comment by csshugs** [comment]
@nenadjelovac A solution would be to provide further variables for the horizontal padding:

``` scss
$inuit-btn-padding-vertical:            halve($inuit-base-spacing-unit) !default;
$inuit-btn-padding-horizontal:          quarter($inuit-base-spacing-unit) !default;
$inuit-btn-padding-vertical--small:     halve($inuit-btn-padding) !default;
$inuit-btn-padding-horizontal--small:   quarter($inuit-btn-padding) !default;
$inuit-btn-padding-vertical--large:     double($inuit-btn-padding) !default;
$inuit-btn-padding-horizontal--large:   $inuit-btn-padding !default;
```

...and assign these further down in the buttons file:

``` scss
.btn {
    padding: $inuit-btn-padding-vertical - $inuit-btn-border-width  $inuit-btn-padding-horizontal - $inuit-btn-border-width;
}
```

And the same with the `--small` and `--large` modifier.

**Comment by florianbouvot** [comment]
@csshugs I really like your solution, least boring than editing every variables ;)

**Comment by csshugs** [comment]
After reviewing it today, I guess this would be slightly better:

``` scss
$inuit-btn-padding-vertical:            halve($inuit-base-spacing-unit) !default;
$inuit-btn-padding-horizontal:          halve($inuit-btn-padding-vertical) !default;
$inuit-btn-padding-vertical--small:     halve($inuit-btn-padding) !default;
$inuit-btn-padding-horizontal--small:   halve($inuit-btn-padding-vertical--small) !default;
$inuit-btn-padding-vertical--large:     double($inuit-btn-padding) !default;
$inuit-btn-padding-horizontal--large:   halve($inuit-btn-padding-vertical--large) !default;
```

**Comment by florianbouvot** [comment]
@csshugs I think it's not a too personal needs (PR) ? It could be useful for `list-ui` and `list-block` too ?

**Comment by csshugs** [comment]
@florianbouvot 

> It could be useful for list-ui and list-block too ?

Yes, but the config then would look like this (for `list-ui`):

``` scss
$inuit-list-ui-padding-vertical:            $inuit-base-spacing-unit !default;
$inuit-list-ui-padding-horizontal:          $inuit-list-ui-padding-vertical !default;
$inuit-list-ui-padding-vertical--tiny:      quarter($inuit-list-ui-padding) !default;
$inuit-list-ui-padding-horizontal--tiny:    $inuit-list-ui-padding-vertical--tiny !default;
$inuit-list-ui-padding-vertical--small:     halve($inuit-list-ui-padding) !default;
$inuit-list-ui-padding-horizontal--small:   $inuit-list-ui-padding-vertical--small !default;
$inuit-list-ui-padding-vertical--large:     double($inuit-list-ui-padding) !default;
$inuit-list-ui-padding-horizontal--large:   $inuit-list-ui-padding-vertical--large !default;
$inuit-list-ui-padding-vertical--huge:      quadruple($inuit-list-ui-padding) !default;
$inuit-list-ui-padding-horizontal--huge:    $inuit-list-ui-padding-vertical--huge !default;
```

plus the rest of the config.

And imagine you want to adjust the padding variable. When you want an equal vertical and horizontal padding, you just need to adjust `$inuit-list-ui-padding-vertical` but that variable also adjusts the horizontal padding. So the naming here is confusing. (And this all applies to the button object, too)

The above was just a suggestion far from being perfect and worth a PR ;-)
I'm not sure about it either.

And we're back at square one and the discussion between **simple as possible and less opinionated vs. one-size-fits-all** (exaggerating a bit here).

**Comment by csshugs** [comment]
Given the above mentioned suggestion with these lots of extra variables, this is surely not what inuitcss is after. 

```
$inuit-btn-namespace:                   $inuit-namespace !default;

$inuit-btn-padding-vertical:            halve($inuit-base-spacing-unit) !default;
$inuit-btn-padding-horizontal:          halve($inuit-btn-padding-vertical) !default;
$inuit-btn-padding-vertical--small:     halve($inuit-btn-padding) !default;
$inuit-btn-padding-horizontal--small:   halve($inuit-btn-padding-vertical--small) !default;
$inuit-btn-padding-vertical--large:     double($inuit-btn-padding) !default;
$inuit-btn-padding-horizontal--large:   halve($inuit-btn-padding-vertical--large) !default;
$inuit-btn-background:                  #4a8ec2 !default;
$inuit-btn-color:                       #fff !default;
$inuit-btn-border-width:                1px !default;
$inuit-btn-border-style:                solid !default;
$inuit-btn-border-color:                $inuit-btn-background !default;
$inuit-btn-radius:                      0 !default;

$inuit-enable-btn--small:               false !default;
$inuit-enable-btn--large:               false !default;
$inuit-enable-btn--full:                false !default;
$inuit-enable-btn--pill:                false !default;
```

As opinionated as the button object is anyway at the moment (background-color etc.), this huge block of variables is just a bit too much and verbose. And as it comes to the button object, this is like something anyone will extend\* anyway a bit in every project (modifier classes for different colors etc.) by herself.

@aaronstezycki **possible solution for your problem:** 
I suggest not to not include it, but to extend\* it in your own `_objects.buttons.scss`. So in your main stylesheet:

``` scss
...
@import "bower_components/inuit-buttons/objects.buttons"; // inuitcss' buttons object
@import "objects.buttons"; // custom button object
```

And respectively in your `_objects.buttons.scss`:

``` scss
$btn-padding-vertical:            halve($base-spacing-unit) !default;
$btn-padding-horizontal:          halve($btn-padding-vertical) !default;

.btn {
    padding: $btn-padding-vertical  $btn-padding-horizontal;
}
```

---

\* **Not** `@extend`

**Comment by csshugs** [comment]
> And as it comes to the button object, this is like something anyone will extend\* anyway a bit in every project (modifier classes for different colors etc.) by herself.

This also might be the reason why buttons are [now considered as a component](https://github.com/inuitcss/inuitcss/blob/87b603e3b60e6d20f9c0a91cd2558f12ff0b298d/components/_example.components.buttons.scss) in the beta version, rather than an object.

Hence, I'll close this issue. It actually is an issue, but not an issue in inuitcss' concerns, since the buttons are actually a bit opinionated, therefore design-related, therefore on components territory, therefore not inuitcss' concerns (anymore).

> It might be that, if I want fine grained control, that I don't include inuit buttons, and just create my own button object?

This actually is the way to go.

**Comment by aaronstezycki** [comment]
I agree, button options and the way they are designed can get rather complicated and verbose!

Although in my particular case, (if you decide to include the buttons object in V6) I suggest leaving out any design related options within inuit altogether (in the future) **OR** set them within a true/false statement. So what I mean by that, is not setting a padding, background-colour, border etc within the default  `.btn` class and having `.btn--tiny`, `.btn--small`, `.btn--large` etc contain the padding styles which are set to false by default, and if users want them enable them they can within a settings file.

This allows me to use any styles within the generic `.btn` class without having to override properties previously set and that way when the css is compiled, the initial padding is not being set twice and overridden, thus not being as DRY as it could be. Hope that makes sense.

---

Kudos to the team, I'm (scarily) infatuated with this project as it unfolds and I'm liking where its going. Good job!

**Comment by csshugs** [comment]
@aaronstezycki 

> I suggest leaving out any design related options within inuit altogether

We'll do for exact this reason. 

> Kudos to the team, I'm (scarily) infatuated with this project as it unfolds and I'm liking where its going. Good job!

❤️
