### ISSUE TITLE
How do you rationalize pixels-as-padding

### ISSUE THREAD

**Issue by jzempel** [inuitcss/objects.buttons#5]
...given your post at http://csswizardry.com/2011/12/measuring-and-sizing-uis-2011-style:

> As I outline in the next section, I don’t actually set font-sizes in ems; I use rems which is essentially ems-with-benefits. What I do set in ems is things to do with type; margin-bottoms on paragraphs, lists, headings and the like; _paddings on buttons_, nav links and promos and other such measurements; borders on promos etc.

Is it because you want the ability to subtract border pixels? I'm wondering if there is a way to achieve both (rem padding + pixel math) with pixel fallback like you use for font-size?

**Comment by csshugs** [comment]
Since this repository is now officially deprecated, I close this.
If this issue is still relevant, please open a new issue in the [new repository](https://github.com/inuitcss/inuitcss).

But thanks for pointing this out!
