### ISSUE TITLE
inherited font styles

### ISSUE THREAD

**Issue by csshugs** [inuitcss/objects.buttons#7]
Can you please give me a use case where `font: inherit` is useful. Because now it always needs an extra html element to assign a font-size to a button.

This won't work:
```html
<button class="btn alpha">Button </button>
```

Instead I have to do:
```html
<button class="btn">
    <span class="alpha">Button</span> 
</button>
```

Is there any reason to that? Otherwise I would suggest to get rid of that declaration.

**Comment by csshugs** [comment]
I was refering to [this declaration](https://github.com/inuitcss/objects.buttons/blob/master/_objects.buttons.scss#L55).

**Comment by florianbouvot** [comment]
+1

**Comment by anselmh** [comment]
Hey, what exactly bothers you about the inheritance from the parent element and can you give an example of why you’re not able to override this directly but need an extra element? As in the comments, it’s useful and sometimes needed when you add custom styling to input elements displaying them as buttons.

**Comment by csshugs** [comment]
As in my example above: When I have a button, either
```html
<input type="submit" class="btn alpha" value="Button" />
```
or
```html
<button class="btn alpha">Button</button>
```
`.alpha` doesn't take affect to assign the `$inuit-heading-size-1` font-size to the button. Instead it inherits its font-size of  `$inuit-base-font-size`, unless the buttons container gets `.alpha` applied:
```html
<div class="alpha">
    <button class="btn">Button</button>
</div>
```
which is firstly just not right to me, because I want to assign the `.alpha` font-size directly to the button and not to its container element, and secondly often a container element is just needless markup and in this case just exists, to assign a font-size to its child element.

I just want to know, when exactly ([as written in the comments](https://github.com/inuitcss/objects.buttons/blob/master/_objects.buttons.scss#L43-L44)) this declaration is necessary.

I'm sure @csswizardry had a specific use case in mind when he wrote this declaration and I'm very curious what this use case looks like. Because for me, the downsides described above prevail to me (maybe because I never ran in that specific, to me unknown use case).

**Comment by anselmh** [comment]
Ah, understand this now. Actually both makes sense. As you guessed, when using a wrapper it’s doing a fine job inheriting the font-size (but inherit is also the default value if it’s not altered anywhere in CSS so it might be dropped indeed).
On the other hand when no wrapper should be applied it’s causing you "trouble". Thanks for clarifying, waiting for input by Harry on if we might drop the declaration.

**Comment by nenadjelovac** [comment]
@csshugs 
>.alpha doesn't take affect to assign the $inuit-heading-size-1 font-size to the button. Instead it inherits its font-size of $inuit-base-font-size, unless the buttons container gets .alpha applied

[Headings are now trumps](https://github.com/inuitcss/trumps.headings) so this particular case should be solved. But I understand your other points.

>I'm sure @csswizardry had a specific use case in mind when he wrote this declaration and I'm very curious what this use case looks like. 

Me too ;)

>Because for me, the downsides described above prevail to me (maybe because I never ran in that specific, to me unknown use case).

+1

**Comment by csshugs** [comment]
Ah brilliant! Thanks @nenadjelovac. I totally missed that it's been switched over to the trumps level already.

Nevertheless:
> I'm sure @csswizardry had a specific use case in mind when he wrote this declaration and I'm very curious what this use case looks like.

I'm still very curious about this point @csswizardry :-)

**Comment by csshugs** [comment]
Closing this, as [this](https://github.com/inuitcss/inuitcss/blob/b158becc1c703656de2065f1741f6040bf0e4f64/components/_example.components.buttons.scss#L13-L14) answered my initial question.
